Support passing `runInstrumentation` flag as gradle argument
Karumi/Shot pull request #237
Opened 2021-07-01 14:26 UTC by SamCosta1

Will allow overriding the configuration set in the gradle file with the commandline argument. 

e.g ./gradlew executeScreenshotTests -PrunInstrumentation=false

### :pushpin: References
* **Issue:** #228 

### :tophat: What is the goal?

Allow toggling the `runInstrumentation` property from the commandline
### How is it being implemented?

Check the gradle properties before defaulting to the usual config.

### How can it be tested?

Can't see a way of writing any tests for this with the current test suite. Not very familiar with scala or with gradle plugins though so I'm happy to look at this again if I'm missing something.

2021-07-01 15:21 UTC, pedrovgs commented
Hey @SamCosta1 thank you so much for your contribution!! Right now we could add tests using the gradle plugin testing framework but I don't think is worth it in this scenario. Could you please ensure you've executed this command ``./gradlew scalaFmtAll`` in order to format all the scala code you've written?

Fun fact, I've developed a similar feature in this branch ``avoid-running-tests-from-command-line-too`` xD But we'll keep your solution, I think it's better 😃

2021-07-01 15:22 UTC, pedrovgs requested changes
Hey @SamCosta1 thank you so much for your contribution!! Right now we could add tests using the gradle plugin testing framework but I don't think is worth it in this scenario. Could you please ensure you've executed this command ./gradlew scalaFmtAll in order to format all the scala code you've written?

Fun fact, I've developed a similar feature in this branch avoid-running-tests-from-command-line-too xD But we'll keep your solution, I think it's better 😃

2021-07-01 15:25 UTC, SamCosta1 commented
Ah I thought I'd run the formatting command but now realise I was running the wrong thing 🤦 , I'll do that now! Thank you!

2021-07-02 06:31 UTC, pedrovgs approved these changes
👏

2021-07-02 06:31 UTC, merged